# alias 'docker=podman'
# alias 'docker-compose=podman-compose'
alias 'ls=ls --color=auto'
alias 'll=ls -la'
alias 'gp=git push'
alias 'gpl=git pull'
alias 'gs=git status'
alias 'gcz=npx git-cz@latest --disable-emoji'